[package]
name = "bh_alloc"
version = "0.2.1"
authors = ["Brian L. Troutwine <brian@troutwine.us>"]
keywords = ["fuzzing", "allocator"]
categories = ["memory-management"]
description = "A fuzzer friendly bump pointer allocator"
license = "MIT"
documentation = "https://docs.rs/bh_alloc/"
repository = "https://github.com/blt/bh_alloc"

[dependencies]
libc = "0.2"

[dev-dependencies]
quickcheck = "0.7"
hashbrown = "0.1"

[[bin]]
path = "src/bin/hello_world.rs"
name = "hello_world"

[[bin]]
path = "src/bin/alloc_and_destroy.rs"
name = "alloc_and_destroy"
